### ==============================
### CHANTS API TEST FILE (VS CODE REST CLIENT)
### ==============================

@baseUrl = http://localhost:3000
@chantId = 69d9039efeae1ae956d95037

### 1. CREATE CHANT(simple)
POST {{baseUrl}}/chants
Content-Type: application/json

{
  "title": "Amazing Grace",
  "category": "adoration",
  "tags": ["lent", "classique"],
  "isPublished": true
}

### 2. CREATE CHANT( avec les medias )
POST {{baseUrl}}/chants
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="coverImage"; filename="image.jpg"
Content-Type: image/jpeg

< ./yess.jpg
--boundary
Content-Disposition: form-data; name="audioUrl"; filename="audio.ogg"
Content-Type: audio/mpeg

< ./audio.ogg
--boundary
Content-Disposition: form-data; name="soprano"; filename="soprano.mp3"

< ./soprano.mp3
--boundary
Content-Disposition: form-data; name="alto"; filename="alto.mp3"

< ./alto.mp3
--boundary
Content-Disposition: form-data; name="tenor"; filename="tenor.mp3"

< ./tenor.mp3
--boundary
Content-Disposition: form-data; name="bass"; filename="bass.mp3"

< ./bass.mp3
--boundary
Content-Disposition: form-data; name="title"

Yesu Azali
--boundary
Content-Disposition: form-data; name="category"

adoration
--boundary
Content-Disposition: form-data; name="tags[]"

lent
--boundary
Content-Disposition: form-data; name="tags[]"

classique
--boundary
Content-Disposition: form-data; name="isPublished"

true
--boundary--

### 3. GET ALL CHANTS
GET {{baseUrl}}/chants

### 4. FILTER CHANTS
GET {{baseUrl}}/chants?category=louange&tag=classique&isPublished=true

### 5. GET CHANT BY ID
GET {{baseUrl}}/chants/{{chantId}}

### 5. GET CHANT BY SLUG
GET {{baseUrl}}/chants/slug/amazing-grace

### 6. UPDATE CHANT( Simple )
PATCH {{baseUrl}}/chants/{{chantId}}
Content-Type: application/json

{
  "category": "louange",
  "isPublished": false
}

### 7. UPDATE CHANT
PATCH {{baseUrl}}/chants/{{chantId}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="coverImage"; filename="new-image.jpg"
Content-Type: image/jpeg

< ./new-image.jpg
--boundary
Content-Disposition: form-data; name="audioUrl"; filename="new-audio.ogg"
Content-Type: audio/mpeg

< ./new-audio.ogg
--boundary
Content-Disposition: form-data; name="soprano"; filename="new-soprano.mp3"

< ./new-soprano.mp3
--boundary
Content-Disposition: form-data; name="title"

Yesu Azali (Remix)
--boundary
Content-Disposition: form-data; name="category"

louange
--boundary
Content-Disposition: form-data; name="tags[]"

rapide
--boundary
Content-Disposition: form-data; name="tags[]"

chorale
--boundary
Content-Disposition: form-data; name="isPublished"

false
--boundary--

### 7. DELETE CHANT
DELETE {{baseUrl}}/chants/{{chantId}}