@baseUrl = http://localhost:3000

POST {{baseUrl}}/chants
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="coverImage"; filename="image.jpg"
Content-Type: image/jpeg

< ./yess.jpg
--boundary
Content-Disposition: form-data; name="audioUrl"; filename="audio.ogg"
Content-Type: audio/mpeg

< ./audio.ogg
--boundary
Content-Disposition: form-data; name="soprano"; filename="soprano.mp3"

< ./soprano.mp3
--boundary
Content-Disposition: form-data; name="alto"; filename="alto.mp3"

< ./alto.mp3
--boundary
Content-Disposition: form-data; name="tenor"; filename="tenor.mp3"

< ./tenor.mp3
--boundary
Content-Disposition: form-data; name="bass"; filename="bass.mp3"

< ./bass.mp3
--boundary
Content-Disposition: form-data; name="title"

Amazing Graces
--boundary
Content-Disposition: form-data; name="category"

adoration
--boundary
Content-Disposition: form-data; name="tags[]"

lent
--boundary
Content-Disposition: form-data; name="tags[]"

classique
--boundary
Content-Disposition: form-data; name="isPublished"

true
--boundary--